apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-node-cpu-alert
  labels:
    role: alert-rules
spec:
  groups:
  - name: demo.rules
    rules:
    - alert: NodeHighCPU
      expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Node {{ $labels.instance }} CPU > 70%"
        description: "Instance {{ $labels.instance }} has CPU usage > 70% for more than 2 minutes."
